from tkinter import *
root = Tk()
#Время и счет урока
Label(text="0",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=0, column=1)
Label(text="1",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=0, column=2)
Label(text="2",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=0, column=3)
Label(text="3",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=0, column=4)
Label(text="4",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=0, column=5)
Label(text="5",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=0, column=6)
Label(text="6",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=0, column=7)
Label(text="7",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=0, column=8)
Label(text="8",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=0, column=9)
Label(text="9",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=0, column=10)
Label(text="10",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=0, column=11)
#пустая строка в углу
Label(text="   ",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=0, column=0)
#Дни
Label(text="Esmaspäev",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=1, column=0)
Label(text="",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=2, column=0)
Label(text="Teisipäev",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=3, column=0)
Label(text="",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=4, column=0)
Label(text="Kolmapäev",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=5, column=0)
Label(text="",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=6, column=0)
Label(text="Neljapäev",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=7, column=0)
Label(text="",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=8, column=0)
Label(text="Reede",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=9, column=0)
Label(text="",font="Arial,50",width=10,height=3,relief=RIDGE).grid(row=10, column=0)

#Нулевой урок
Label(text="   ").grid(row=2, column=2)
Label(text="   ").grid(row=3  , column=2)
Label(text="   ").grid(row=4, column=2)
Label(text="   ").grid(row=5  , column=2)
Label(text="   ").grid(row=6, column=2)
Label(text="   ").grid(row=7  , column=2)
Label(text="   ").grid(row=8, column=2)
Label(text="   ").grid(row=9  , column=2)

#Понедельник row=вниз column=право
Label(text=" ").grid(row=1, column=3)
Label(text="EK(Tugiõpe)",bg="pink",font="Arial,50",width=11,height=5,relief=RIDGE).grid(row=2, column=2)
Label(text="Logistikateenused ja varude juhtmine",bg="green",font="Arial,50",width=23,height=8,relief=RIDGE).grid(row=1, column=3,columnspan=2,rowspan=2)
Label(text="Matemaatika",bg="pink",font="Arial,50",width=11,height=8,relief=RIDGE).grid(row=1, column=5,rowspan=2)
Label(text="Matemaatika",bg="pink",font="Arial,50",width=11,height=8,relief=RIDGE).grid(row=1, column=6,rowspan=2)
Label(text="   ").grid(row=2, column=7)
Label(text="   ").grid(row=1, column=7)   
Label(text="Keel ja kirjandus",bg="green",font="Arial,50",width=11,height=8,relief=RIDGE).grid(row=1, column=8,rowspan=2)
Label(text="Keel ja kirjandus",bg="green",font="Arial,50",width=11,height=8,relief=RIDGE).grid(row=1, column=9,rowspan=2)
Label(text="Matemaatika(Tugiõpe)",bg="pink",font="Arial,50",width=11,height=8,relief=RIDGE).grid(row=1, column=10,rowspan=2)

Label(text="   ").grid(row=1, column=11)
Label(text="   ").grid(row=2, column=11)

#Вторник
Label(text="Tugiõpe(Keemia)",bg="pink",font="Arial,50",width=11,height=6,relief=RIDGE).grid(row=3, column=2,rowspan=2)
Label(text="Programmeerimise alused(Eesti keel)",bg="lightblue",font="Arial,50",width=35,height=6,relief=RIDGE).grid(row=3, column=3,columnspan=3,rowspan=2)
Label(text="   ").grid(row=3, column=6)
Label(text="   ").grid(row=4, column=6)
Label(text="Fuiüska",bg="pink",font="Arial,50",width=23,height=6,relief=RIDGE).grid(row=3, column=7,columnspan=2,rowspan=2)
Label(text="   ").grid(row=3, column=9)
Label(text="   ").grid(row=4, column=9)
Label(text="   ").grid(row=3, column=10)
Label(text="   ").grid(row=4, column=10)
Label(text="   ").grid(row=3, column=11)
Label(text="   ").grid(row=4, column=11)

#Среда
Label(text="EK(Tugiõpe)",bg="pink",font="Arial,50",width=11,height=5,relief=RIDGE).grid(row=5, column=2)
Label(text="   ").grid(row=6, column=2)
Label(text="Kunstiained(Eesti keel)",bg="purple",font="Arial,50",width=23,height=8,relief=RIDGE).grid(row=5, column=3,columnspan=2,rowspan=2)
Label(text="   ").grid(row=5, column=5)
Label(text="   ").grid(row=6, column=5)
Label(text="Kehaline kasvatus",bg="purple",font="Arial,50",width=23,height=8,relief=RIDGE).grid(row=5, column=6,columnspan=2,rowspan=2)
Label(text="   ").grid(row=5, column=8)
Label(text="   ").grid(row=6, column=8)
Label(text="   ").grid(row=5, column=9)
Label(text="   ").grid(row=6, column=9)
Label(text="   ").grid(row=5, column=10)
Label(text="   ").grid(row=6, column=10)
Label(text="   ").grid(row=5, column=11)
Label(text="   ").grid(row=6, column=11)

#Четверг
Label(text="Logistikateenused ja varude juhtmine",bg="green",font="Arial,50",width=23,height=8,relief=RIDGE).grid(row=7, column=2,columnspan=2,rowspan=2)
Label(text="   ").grid(row=7, column=4)
Label(text="   ").grid(row=8, column=4)
Label(text="Programmeerimise alused(Eesti keel)",bg="lightblue",font="Arial,50",width=23,height=8,relief=RIDGE).grid(row=7, column=5,columnspan=2,rowspan=2)
Label(text="Ing keel",bg="beige",font="Arial,50",width=11,height=4,relief=RIDGE).grid(row=7, column=7)
Label(text="Ing keel",bg="beige",font="Arial,50",width=11,height=4,relief=RIDGE).grid(row=7, column=8)
Label(text="Arenduskeskkonna loomine",bg="red",font="Arial,50",width=23,height=4,relief=RIDGE).grid(row=8, column=7,columnspan=2)
Label(text="Arenduskeskkonna loomine",bg="red",font="Arial,50",width=23,height=4,relief=RIDGE).grid(row=7, column=9,columnspan=2)
Label(text="Eesti keel",bg="grey",font="Arial,50",width=11,height=4,relief=RIDGE).grid(row=8, column=9)
Label(text="Eesti keel",bg="grey",font="Arial,50",width=11,height=4,relief=RIDGE).grid(row=8, column=10)
Label(text="Rühmajuha tund",bg="pink",font="Arial,50",width=11,height=4,relief=RIDGE).grid(row=7, column=11)

#Пятница
Label(text="Eesti keel",bg="purple",font="Arial,50",width=11,height=4,relief=RIDGE).grid(row=9, column=2)
Label(text="Eesti keel",bg="purple",font="Arial,50",width=11,height=4,relief=RIDGE).grid(row=9, column=3)
Label(text="Arenduskeskkonna loomine",bg="red",font="Arial,50",width=23,height=4,relief=RIDGE).grid(row=9, column=9,columnspan=2)
Label(text="Programmeerimise alused(Eesti keel)",bg="lightblue",font="Arial,50",width=58,height=8,relief=RIDGE).grid(row=9, column=2,columnspan=9,rowspan=2)
Label(text="Ing keel",bg="green",font="Arial,50",width=11,height=4,relief=RIDGE).grid(row=10, column=9)
Label(text="Ing keel",bg="green",font="Arial,50",width=11,height=4,relief=RIDGE).grid(row=10, column=10)
Label(text="Arenduskeskkonna loomine",bg="red",font="Arial,50",width=23,height=4,relief=RIDGE).grid(row=10, column=2,columnspan=2)
root.mainloop()